nifi:
  image: sthysel/apache-nifi
  environment:
    - KEYSTORE_PATH=/certs/keystore.jks
    - KEYSTORE_TYPE=JKS
    - KEYSTORE_PASSWORD=${NIFI_PASS}
    - TRUSTSTORE_PATH=/certs/truststore.jks
    - TRUSTSTORE_PASSWORD=${NIFI_PASS}
    - TRUSTSTORE_TYPE=JKS
  volumes:
    - ${NIFI_CERT_PATH}:/certs
    - authorized-users.xml:/nifi/conf/authorized-users.xml
